Repository EXPRESSFOOD2/apiexpressfood, pull requests merged in 2023-02, with the labels that each got.

#93 Con seeds & Docs
  Doc_Rutas.md
  src/controllers/menuItem/menuItem-get_controller.js
  src/db.js
  src/models/Tag.js
  src/models/TagsMenuItems.js
  src/models/utils/Tag-ErrorMSGs.js
  src/seeds/Menu-seed.js
  src/seeds/MenuTags-seed.js
  src/seeds/Tag-seed.js
  src/seeds/index.js
Labels: enhancement

#101 Modificación retorno de la función userLoginController
  src/controllers/user/user-get-login_controller.js
Labels: enhancement

#94 Crea Model Order
  src/controllers/HashFunction/security.js
  src/middleware/ingredients_middleware.js
  src/models/Order.js
  src/models/OrdersMenu.js
  src/models/utils/Order-ErrorMSGs.js
  src/seeds/User-seed.js
  src/seeds/index.js
Labels: enhancement

#106 Feature/rework ingredient recipe menu item logics
  cambios.md
  src/controllers/HashFunction/security.js
  src/controllers/Utils/aux_controller.js
  src/controllers/ingredient/ingredient-delete_controller.js
  src/controllers/ingredient/ingredient-get_controller.js
  src/controllers/ingredient/ingredient-patch_controler.js
  src/controllers/ingredient/ingredient-post_controller.js
  src/controllers/menuItem/menuItem-delete_controller.js
  src/controllers/menuItem/menuItem-get_controller.js
  src/controllers/menuItem/menuItem-patch_controler.js
  src/controllers/menuItem/menuItem-post_controller.js
  src/controllers/recipe/recipe-delete_controller.js
  src/controllers/recipe/recipe-get_controller.js
  src/controllers/recipe/recipe-patch_controller.js
  src/controllers/recipe/recipe-post_controller.js
  src/db.js
  src/middleware/ingredients_middleware.js
  src/middleware/menu_middleware.js
  src/middleware/recipes_middleware.js
  src/models/Ingredient.js
  src/models/MenuItem.js
  src/models/Recipe.js
  src/models/Store.js
  src/models/utils/Ingredient-ErrorMSGs.js
  src/models/utils/Recipe-ErrorMSGs.js
  src/models/utils/Store-ErrorMSGs.js
  src/seeds/Ingredient-seed.js
  src/seeds/Menu-seed.js
  src/seeds/Recipe-layer1-seed.js
  src/seeds/User-seed.js
Labels: enhancement

#108 Feature/build tags
  .env.example
  cambios.md
  src/controllers/HashFunction/security.js
  src/controllers/Utils/aux_controller.js
  src/controllers/menuItem/menuItem-delete_controller.js
  src/controllers/recipe/recipe-get_controller.js
  src/controllers/tag/tag-delete_controller.js
  src/controllers/tag/tag-get_controller.js
  src/controllers/tag/tag-patch_controller.js
  src/controllers/tag/tag-post_controller.js
  src/db.js
  src/middleware/ingredients_middleware.js
  src/middleware/recipes_middleware.js
  src/middleware/tags_middleware.js
  src/models/Tag.js
  src/models/utils/Tag-ErrorMSGs.js
  src/routes/index.js
  src/routes/tags/tags_delete.js
  src/routes/tags/tags_get.js
  src/routes/tags/tags_patch.js
  src/routes/tags/tags_post.js
Labels: enhancement

#119 menu/get Tags es ahora un Array de strings
  src/controllers/menuItem/menuItem-get_controller.js
  src/routes/index.js
Labels: enhancement

#123 Asocia User a Store
  package.json
  src/controllers/HashFunction/security.js
  src/controllers/Utils/Store-create_controller.js
  src/controllers/recipe/recipe-get_controller.js
  src/controllers/recipe/recipe-post_controller.js
  src/controllers/user/user-post_controller.js
  src/db.js
  src/models/IngredientsRecipes.js
  src/models/Order.js
  src/models/Store.js
  src/models/UsersStores.js
  src/routes/login-google.js
Labels: enhancement

#128 Genera Ordenes de compra
  src/controllers/HashFunction/security.js
  src/controllers/Payments/payments-controller.js
  src/controllers/order/order-post_controller.js
  src/controllers/user/user-post_controller.js
  src/middleware/payments-middleware.js
  src/models/Order.js
  src/routes/payments/payments-router.js
  src/seeds/index.js
Labels: enhancement

#131 Modificaciones en menu_middleware y menuItem-get_controller
  src/controllers/menuItem/menuItem-get_controller.js
  src/middleware/menu_middleware.js
Labels: bug

#133 Feature/paymant order v2
  .env.example
  sdaasd
  src/controllers/Payments/payments-controller.js
  src/controllers/Payments/payments-failure-controler.js
  src/controllers/Payments/payments-success-controler.js
  src/controllers/order/order-post_controller.js
  src/middleware/menu_middleware.js
  src/middleware/payments-middleware.js
  src/models/Order.js
  src/models/utils/constants.js
  src/routes/payments/payments-router.js
Labels: bug, enhancement

#144 Crear rutas, mw y ctrls
  src/controllers/order/order-get_controller.js
  src/controllers/order/order-patch_controller.js
  src/middleware/order_middleware.js
  src/routes/index.js
  src/routes/orders/order-get.js
  src/routes/orders/order-patch.js
Labels: enhancement
